/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as OurPromiseRouteImport } from './routes/our-promise'
import { Route as GourmetRouteImport } from './routes/gourmet'
import { Route as FreshProduceRouteImport } from './routes/fresh-produce'
import { Route as BakeryRouteImport } from './routes/bakery'
import { Route as IndexRouteImport } from './routes/index'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const OurPromiseRoute = OurPromiseRouteImport.update({
  id: '/our-promise',
  path: '/our-promise',
  getParentRoute: () => rootRouteImport,
} as any)
const GourmetRoute = GourmetRouteImport.update({
  id: '/gourmet',
  path: '/gourmet',
  getParentRoute: () => rootRouteImport,
} as any)
const FreshProduceRoute = FreshProduceRouteImport.update({
  id: '/fresh-produce',
  path: '/fresh-produce',
  getParentRoute: () => rootRouteImport,
} as any)
const BakeryRoute = BakeryRouteImport.update({
  id: '/bakery',
  path: '/bakery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bakery': typeof BakeryRoute
  '/fresh-produce': typeof FreshProduceRoute
  '/gourmet': typeof GourmetRoute
  '/our-promise': typeof OurPromiseRoute
  '/recipes': typeof RecipesRoute
  '/shop': typeof ShopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bakery': typeof BakeryRoute
  '/fresh-produce': typeof FreshProduceRoute
  '/gourmet': typeof GourmetRoute
  '/our-promise': typeof OurPromiseRoute
  '/recipes': typeof RecipesRoute
  '/shop': typeof ShopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bakery': typeof BakeryRoute
  '/fresh-produce': typeof FreshProduceRoute
  '/gourmet': typeof GourmetRoute
  '/our-promise': typeof OurPromiseRoute
  '/recipes': typeof RecipesRoute
  '/shop': typeof ShopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bakery'
    | '/fresh-produce'
    | '/gourmet'
    | '/our-promise'
    | '/recipes'
    | '/shop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bakery'
    | '/fresh-produce'
    | '/gourmet'
    | '/our-promise'
    | '/recipes'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/bakery'
    | '/fresh-produce'
    | '/gourmet'
    | '/our-promise'
    | '/recipes'
    | '/shop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BakeryRoute: typeof BakeryRoute
  FreshProduceRoute: typeof FreshProduceRoute
  GourmetRoute: typeof GourmetRoute
  OurPromiseRoute: typeof OurPromiseRoute
  RecipesRoute: typeof RecipesRoute
  ShopRoute: typeof ShopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-promise': {
      id: '/our-promise'
      path: '/our-promise'
      fullPath: '/our-promise'
      preLoaderRoute: typeof OurPromiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gourmet': {
      id: '/gourmet'
      path: '/gourmet'
      fullPath: '/gourmet'
      preLoaderRoute: typeof GourmetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fresh-produce': {
      id: '/fresh-produce'
      path: '/fresh-produce'
      fullPath: '/fresh-produce'
      preLoaderRoute: typeof FreshProduceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bakery': {
      id: '/bakery'
      path: '/bakery'
      fullPath: '/bakery'
      preLoaderRoute: typeof BakeryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BakeryRoute: BakeryRoute,
  FreshProduceRoute: FreshProduceRoute,
  GourmetRoute: GourmetRoute,
  OurPromiseRoute: OurPromiseRoute,
  RecipesRoute: RecipesRoute,
  ShopRoute: ShopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
